//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XMLSchema.xsd", IsNullable=false)]
public partial class XACTPatchContent {
    
    private XACTPatchContentInstrument[] instrumentField;
    
    private int countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Instrument")]
    public XACTPatchContentInstrument[] Instrument {
        get {
            return this.instrumentField;
        }
        set {
            this.instrumentField = value;
        }
    }
    
    /// <remarks/>
    public int Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema.xsd")]
public partial class XACTPatchContentInstrument {
    
    private sbyte patchNumberField;
    
    private bool repeatField;
    
    private bool stretchRangeField;
    
    private bool stretchRangeFieldSpecified;
    
    private sbyte attackSpeedField;
    
    private bool attackSpeedFieldSpecified;
    
    private sbyte releaseSpeedField;
    
    private string nameField;
    
    /// <remarks/>
    public sbyte PatchNumber {
        get {
            return this.patchNumberField;
        }
        set {
            this.patchNumberField = value;
        }
    }
    
    /// <remarks/>
    public bool Repeat {
        get {
            return this.repeatField;
        }
        set {
            this.repeatField = value;
        }
    }
    
    /// <remarks/>
    public bool StretchRange {
        get {
            return this.stretchRangeField;
        }
        set {
            this.stretchRangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StretchRangeSpecified {
        get {
            return this.stretchRangeFieldSpecified;
        }
        set {
            this.stretchRangeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public sbyte AttackSpeed {
        get {
            return this.attackSpeedField;
        }
        set {
            this.attackSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AttackSpeedSpecified {
        get {
            return this.attackSpeedFieldSpecified;
        }
        set {
            this.attackSpeedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public sbyte ReleaseSpeed {
        get {
            return this.releaseSpeedField;
        }
        set {
            this.releaseSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}
